# https://kubernetes.io/docs/admin/extensible-admission-controllers/

apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: denyimages
webhooks:
  - name: team11.hackathon.com
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    failurePolicy: Ignore
    clientConfig:
      service: 
        name: webhook
        namespace: default
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyRENDQVpRQ0NRQzJLRURWTEpNSGhqQU5CZ2txaGtpRzl3MEJBUXNGQURBWE1SVXdFd1lEVlFRRERBeGgKWkcxcGMzTnBiMjVmWTJFd0lCY05NVGt3TmpBME1EQTBNVEE1V2hnUE1qSTVNekF6TVRrd01EUXhNRGxhTUJjeApGVEFUQmdOVkJBTU1ER0ZrYldsemMybHZibDlqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQU1KL0JFdlQvdlN0Y2ErR3hTQ0JUNUlVTllWM0lWcEQ4QjhWSlhLckVMbEtEcTJWOVNPQnlnVU0KUUphTWJMeGNjdTVlSVROVnlucEU0YjRDZmE0MDFmNVFHM3dySTFjNnNGSDZkTE4ra013eFd1UEVvTFJ4RFJoOApVc2tSNGZVOGtMdXV2T0ZZT3ZMb2R2Tk9vbGhlVnhhbTQvaThNVTFyMHYrZlc2elN3ajJpejVYaER5SEh5bmVECjdlZ3o0b2pyeC9HclpiQURGYmUwWEUraFpsdERLRk9KZ2w2ZWU1aDZlbVFPUnpSMjFrWnJwNEhjWXBhYTZsdG4KU2hjVW0zSjM0Z0JNZ2V5aGEzdDk1R0tJSEZBYmVOWmk1aWt0Y0tBbkFLdUlycnZQODBTdVh1WnJHeW94RkNGdAo0YkVoMzd5eCs2UGEvVk9sazhRVnpSNjR1dm9nSnBrQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBCkdRTWxvZjZ3TUhmYW9IRlhVRlIvQjVZSkJqUnBvTjBhYXJ4bjFjazZhck1EcUg3RFlBTHFpK05EdTBUTzVRejQKNFQzUllOU0NlNkdWbFVFdlpUNGZmMzdYVGRTTUxZQ29VU21YcGFadXNkbFk1RnJRR2IyWDJseFJqMkJ3ZStaVQpjam5IU1dwNUpkb0czMHRZazNWNmdQc3NwQXpGOE9ub1NJZ251NXJLK2hXbEdLZ0NvdlNVSlI1TENQT0w5Vnp4CmVSalp0aG1tbXZIWkhZc0lEUUd0dFZDVTRsT09EN3B4SWhBWlVUY0cySlpQamNHUk5jMjdMZEdFY2RuTHkrWUIKUjJQMFRkL05CcFRaakp4dVZvQW51a0trQnNlbll2YUZtcEpEeUR4bm5WOFFrd0JONnNYclBxS2x4SXEwRzR6KwpGYmU1bHRHQWd4YWxHeEhZbnBweE1RPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
